version: '3.1'

services:
  spring-api1:
    build: .
    hostname: spring-api1
    ports:
      - "8080:8080"
    networks:
      - todo-api
    depends_on:
     - db-postgresql

  db-postgresql:
    image: postgres:15.2-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    networks:
      - todo-api


networks:
  todo-api: